force-app/main/default/objects/Cosecha__c/Cosecha__c.object-meta.xml
<CustomObject>
    <label>Cosecha</label>
    <nameField>
        <label>Cosecha Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cosechas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cosecha__c/fields/Fecha_cosecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha_cosecha__c</fullName>
    <label>Fecha cosecha</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cosecha__c/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <label>Lote</label>
    <referenceTo>Lote__c</referenceTo>
    <relationshipLabel>Cosechas</relationshipLabel>
    <relationshipName>Cosechas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cosecha__c/fields/Notas__c.field-meta.xml
<CustomField>
    <fullName>Notas__c</fullName>
    <label>Notas</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Cosecha__c/fields/Peso_Kg__c.field-meta.xml
<CustomField>
    <fullName>Peso_Kg__c</fullName>
    <label>Peso Kg</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lote__c/Lote__c.object-meta.xml
<CustomObject>
    <label>Lote</label>
    <nameField>
        <label>Lote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RegistrarCosechaController.cls
public with sharing class RegistrarCosechaController {
    
    @AuraEnabled
    public static void crearCosecha(Id loteId, Decimal peso, Date fecha, String notas) {
        try {
            Cosecha__c nuevaCosecha = new Cosecha__c();
            nuevaCosecha.Lote__c = loteId;
            nuevaCosecha.Peso_Kg__c = peso;
            nuevaCosecha.Fecha_cosecha__c = fecha;
            nuevaCosecha.Notas__c = notas;
            
            insert nuevaCosecha;
        } catch (Exception e) {
            throw new AuraHandledException('Error al registrar la cosecha: ' + e.getMessage());
        }
    }
}